# The image will be at ghcr.io/yourusername/name
name: ab-desktop

# The native container image to build on top of
# images. 
# Warning: Non-uBlue images might function unexpectly
base-container: ghcr.io/ab-configs/silverblue-main

# What fedora version to use. Use an explicit version or `latest`.
# If you use `latest`, you will be automatically updated
# to the next major version assuming the image you're using as your base container
# builds with the tag (all uBlue images do this). 
fedora-version: 39

# This description will be visible in the container metadata
description: Rawhide image for abbra desktop

# These rpms will be installed from the fedora repository
# using rpm-ostree and will be preinstalled in the final image
rpms:
  - python3-pip # needed for yafti (the first boot installer)
  - evince
  - powertop
  - fedora-packager-kerberos
  - setools-console
  - qemu-system-x86
  - qemu-img
  - epson-inkjet-printer-escpr2
  - epson-inkjet-printer-escpr
  - foomatic
  - foomatic-db
  - foomatic-db-ppds
  - sane-backends-drivers-scanners
  - sane-backends
  - sane
  - xsane

# These Flatpaks (from flathub) will be available for install on boot
# this is just an example selection.
# If you leave this empty you can use yafti for post-boot installation
flatpaks:
  - org.mozilla.firefox
  - org.mozilla.Thunderbird
  - com.mattjakeman.ExtensionManager
  - org.libreoffice.LibreOffice
  - org.gnome.DejaDup
  - org.gustavoperedo.FontDownloader
  - com.github.tchx84.Flatseal
  - io.github.celluloid_player.Celluloid
